nom = input("Tapez votre nom : ")
print("Bonjour ", nom, " !")
n = int(input("Saisissez un entier : "))
print("Le type de la variable n :", type(n))
x = float(input("Saisissez un flottant : "))
print("Le type de la variable x :", type(x))
print(x)
x = eval(input("Saisir par exemple 3/4 : "))
print("Le type de la variable x :", type(x))
print(x)
